### ISSUE TITLE
static media folder

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#178]
Greetings, 

I'm excitedly on the cusp of pushing some files. When making these helpfile/overview/reference pages I often have both audio and images that are paired together. If/when in the future I will update this media, I want to be able to go to just one folder to replace the media items. Right now I would have to go to both the audio and images folder.

Can I instead, inside of the static folder, just make folder called "buf-nmf-overview" and put both audio and images in there?

I notice there's an overviews folder but that looks quite empty, then there's an examples folder that has some media for an overview in it so I'm unclear on what the protocol should be.

thanks!

**Comment by jamesb93** [comment]
Ah yeah on the surface it can be somewhat contradictory.

`/examples` is for files associated with tutorial videos

`/img`, `/audio` were the first few folders I made when there wasn't as much in there. For now just avoid these as stuff needs to be shifted into more explicit locations. I think if one of the FluCoMa example sound files they should be put into `/audio` though as they are general use.

I think that you should make a folder in either `/examples` or `/overviews` and keep your video and audio bundled in that directory. I would avoid making folders for specific articles just under static as it will eventually be arduous to refactor and track which folder belongs to which section of the site.

If the resources are just so they can be soaked up in the HTML, rather than shared, it doesn't really matter where you put them as they can be moved and redirected internally later.

**Comment by tedmoore** [comment]
thank you!
