### ISSUE TITLE
installation links and content disappear

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#228]
this was the day after the workshop which is good, but I reckon it is an error.

**Comment by jamesb93** [comment]
I need more information if I am to try track down bugs related to learn. 

Information which is useful:

1. What you tried to do and in what order. In this scenario something like: "I went to learn.flucoma.org and then tried to click a specific link but the loading failed with a 404 message" is critically different from "I typed in learn.flucoma.org/installation/sc and got a 403 error".
2. What you expected it to do in light of what happened
3. The operating system and browser (version) used
4. The time that you tried to do it so it can be compared against the build and the nginx logs.

I am unable to reproduce regardless but I am not entirely certain what the problem is too.
