### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#274]
I had a meeting end of last week with a poweruser of other packages who was struggling with the basics of our interface whilst doing basic MLP stuff... so I asked how was spent the learning time and it became clear that our learn platform is missing a triage for first arrival - a sort of first steps at the top, when someone want to learn and doesn't know where to start in the forest of amazing feature we have.

an idea would be to pin at the top of learn a 'first steps - a tutorial' article where we can point at a curated cursus (maybe we optional start points - for instance

1. mlp-class
2. mlp-reg
3. viz2d (in 5)
4. audio query (in 3)

or alternatively 3-4-1-2 but at least knowing that after the 101s the dataset, buffer i/o, slicer, descriptors, etc (we know the list of knowledge someone needs to start to make sense of our ecosystem) is covered. we could say that explicitly as a start point of that article and point at the curated order of things already there (which might trigger detours but people could come back to the tutorial plan as an anchor...)

anyway, it was clear that while our offer is great and generous, it starts to be hard to know where to start.

comments?

**Comment by jdchart** [comment]
I think it was on the horizon to add a "Getting Started" tab, especially now that the installation stuff had been taken off the front page, and this makes sense as to being on there.

These subjects are :
- good cause they get people excited and doing interesting things.
- but perhaps daunting because they sound complicated, and also are very specific (people may not realise that stuff they need to know is in there).

Maybe there should be a "getting started with flucoma" tutorial that comes first, that doesn't mention complicated things like MLP regressors, or specific things like 2d corpus explorers, that covers all the basic stuff you need to know (buffer paradigm, slices layers objects, datasets etc).

**Comment by jamesb93** [comment]
> I think it was on the horizon to add a "Getting Started" tab, especially now that the installation stuff had been taken off the front page, and this makes sense as to being on there.
> 
> These subjects are :
> 
> * good cause they get people excited and doing interesting things.
> * but perhaps daunting because they sound complicated, and also are very specific (people may not realise that stuff they need to know is in there).
> 
> Maybe there should be a "getting started with flucoma" tutorial that comes first, that doesn't mention complicated things like MLP regressors, or specific things like 2d corpus explorers, that covers all the basic stuff you need to know (buffer paradigm, slices layers objects, datasets etc).

Yep getting started is on the horizon @tremblap. @tedmoore and I were trying to chart a course and provide a way for people to get over the start-a-phobia of the package by making the entire cursus some kind of map (much like the sklearn one for choosing one's algo).

**Comment by jamesb93** [comment]
I renamed the issue BTW, rather than make a new one as its clear that getting started needs to unfold in its own way now from here.

**Comment by jdchart** [comment]
Have started a PR for this #285

**Comment by jamesb93** [comment]
In the end, we made a getting started page: https://learn.flucoma.org/getting-started

Looks like this can be closed.
