### ISSUE TITLE
UMAP

### ISSUE THREAD

**Issue by jamesb93** [flucoma/learn-website#41]

**Comment by jamesb93** [comment]
Working on this in https://github.com/flucoma/learn-website/tree/content/umap

I think that a 2d chart.js approach would be fine, over the complexity of using three.js. A working example is presented at ac8f02fe28f63fb9c1769760f203050a79f1dc84 but I think that the pedagogical value of 3d UMAP is pretty nebulous (considering we cannot visualise 4d let alone comprehend it). Something that uses colour, shape and metaphor ala https://pair-code.github.io/understanding-umap/

**Comment by jamesb93** [comment]
Things to borrow...

Figure 3
Figure 4
Figure 5 but with FluCoMa logo :)

How to (mis)read UMAP
Distances don't mean anything in the result

**Comment by jamesb93** [comment]
Others things to hit home on are:

1) It is a balance of local and global space
2) Marriage of the model and your data i.e should you normalise/standardise before going in (it depends https://github.com/lmcinnes/umap/issues/66)
3) You can't transform out of UMAP back to the original space. You can however cheat with a kd-tree and lookup via ID's n stuff

**Comment by jamesb93** [comment]
https://github.com/PAIR-code/scatter-gl

**Comment by tedmoore** [comment]
This is beautiful and fun to play with! I have a few thoughts re: terminology.
- Here: `It allows you to take high-dimensional data and compress it into a lower-dimensional representation.` I'm not sure about the word `compress` because it brings to mind a dynamic range compressor and/or mp3s, so maybe "embed", or "represent in lower dimensions"?
- Instead of `dealt with` I would prefer "dimensionally reduced"
- I think the `Smoothing` parameter should be hidden because it isn't exposed in our object. @weefuzzy @tremblap , Is it a "hard coded" value in our implementation? Maybe this also just hard codes to that?
- When the page loads I find the colored points in 2D space a little confusing. Are these my 2D points? Is this the result of the algorithm? If the randomly generated 3D points are used for the RGB, then why are they spread out randomly in 2D? I understand this is how the algorithm is initiated, but how about if there's a button like "Create UMAP's Randomized Initialization" and then the dots appear?
- In `mindist` I think we should specify what `small` and `bigger` values are.
- For `numneighbours` I think there's one more piece to add. When it says `It is literally enforcing how many neighbouring points UMAP needs to consider.`, we should say how it considers them and what it is considering them for...
- `As such, performing more or less iterations will drastically effect the result.` How will it affect the result? It will be good to give the user some framework of why they would increase or decrease this parameter. Could be a nice place to tie in with neural networks as well.
- `It can be illuminating to know how other dimension algorithms work too, as each technique fails and succeeds in different ways. Furthermore, this Distill article, “How to Use t-SNE Effectively” discusses effective approaches to using t-SNE, another non-linear dimension-reduciton algorithm.` Personally, I would remove the tSNE pointer since it's not in our toolkit. Maybe in this spot we can link to other dimension reduction algorithms in our package and compare the results of those?

**Comment by jamesb93** [comment]
Thanks for this. It definitely tightens things up. I agree that the shift from 3D-2D is quite abstract. Perhaps a 3D plot that becomes 2D would be better although it adds some technical shifting.

The only thing I disagree with is pointing to other algorithms. IMO, it is rich to create bridges to the world outside FluCoMa – I certainly found my way into this stuff via a mixture of FluCoMa and Python and creating a "walled garden" of objects doesn't seem to engender that kind of cross-environment exploration.

I'm working on this stuff in this PR:

https://github.com/flucoma/learn-website/pull/71
