### ISSUE TITLE
NoveltySlice help page references image that isn't there

### ISSUE THREAD

**Issue by MattS6464** [flucoma/learn-website#426]
NoveltySlice help page states:

"Below is a depiction of a novelty curve, computed on the self-similarity matrix you can see above with a kernel size of 41. The detected peaks (read slice points) that come out of this are marked in red."

There are no images below this text.

**Comment by jamesb93** [comment]
I wrote this file, so I am sure that two things could have happened.

- I planned to put something in the `<NoveltyCurve/>` component and forgot or never got time to do it
- I did and it got mangled by `git`.

I checked through the history of that file and I was unable to see any meaningful content in that component.

I'd suggest two paths forward:

1. Edit the text so that it no longer appears in the rendered HTML, close this issue and then create a new issue that tracks the creation of a new component. @fearn-e you might be interested in doing some of this work.
2. Fix it all in one go by creating a component that does what I said it did.

**Comment by MattS6464** [comment]
@jamesb93 ,from where I've just looked, in `learn-website/src/routes/(content)/reference/noveltyslice` there is a `NoveltyCurve.svelte` but the file is completely empty. I assume this is the file being included in line 33 of `+page.svx` (under the same file path).

The ssm image is working in the reference file, and in `learn-website/static/reference/noveltyslice` there's an `ssm.json` and `ssm.svg` but only a `curve.json` with no `curve.svg`. 
Could this have caused the issue? I'm not too familiar with these files so I thought it best to ask before committing to either of your solutions.

**Comment by jamesb93** [comment]
Yes exactly. The component (`NoveltyCurve.svelte` is referred to as a component) is empty, for some reason I can't recall. It certainly was always empty as I checked in the `git` history so I imagine I planned to put something in at some point but never got around to it.
